# Generated by Django 4.2 on 2023-04-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='nbPool',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='nbTeampPool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='beg_date',
            field=models.DateTimeField(null=True, verbose_name='Date began'),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Date ended'),
        ),
    ]
