# Generated by Django 4.2 on 2023-04-17 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournoi_location_tournoi_nbpool_tournoi_nbteamppool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='beg_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date began'),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date ended'),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
