# Generated by Django 4.2 on 2023-04-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournoi_beg_date_alter_tournoi_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trainer', models.CharField(max_length=200)),
                ('players', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Poule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poolId', models.IntegerField(default=0)),
                ('teams', models.ManyToManyField(to='tournaments.equipe')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournoi')),
            ],
        ),
    ]
