# Generated by Django 4.2 on 2023-04-19 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_equipe_poule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('goals1', models.IntegerField(null=True)),
                ('goals2', models.IntegerField(null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.poule')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='tournaments.equipe')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='tournaments.equipe')),
            ],
        ),
    ]
