# Generated by Django 4.2 on 2023-04-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goals1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
