# Generated by Django 4.2 on 2023-04-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_commentaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaire',
            options={'ordering': ['date']},
        ),
    ]
